### ISSUE TITLE
I2C address 0x35

### ISSUE THREAD

**Issue by Hccd2022** [helium/gateway_mfr#12]
Hi Sir,

If I am using a ECC608 I2C address 0x35, how to change the script?

**Comment by madninja** [comment]
use gateway-mfr-rs, not this legacy repository

**Comment by Hccd2022** [comment]
Thanks, will try later.

In addition, the one on hand is ATECC608B-TNGTLSU-G and the configuration zone is already locked.
Can I use it for Helium miner?

**Comment by madninja** [comment]
> Thanks, will try later.
> 
> In addition, the one on hand is ATECC608B-TNGTLSU-G and the configuration zone is already locked. Can I use it for Helium miner?

If you can run gateway-mfr-rs test and bench on it, it should be good, but iirc that part is aimed at TLS support and not configured correctly for Helium's use of ECC
