### ISSUE TITLE
question for gateway_mfr run in ARM device

### ISSUE THREAD

**Issue by andrewintw** [helium/gateway_mfr#6]
Hi, we are preparing the HIP19 and we have a question for the gateway_mfr.

We had porting erlang to our target device but still have problem for the porting gateway_mfr.

I tried to build gateway_mfr on my x86 Linux environment and the gateway_mfr is actually a script file.

Do we need to cross compile the gateway_mfr or just copy all of the "_build/prod/rel" from x86 linux environment  to our target device?

Best,
Andrew

**Comment by madninja** [comment]
I would suggest using https://github.com/helium/gateway-mfr-rs as a replacement. It cross compiles easier and should work mostly the same
